# Generated by Django 5.0.14 on 2026-08-18 14:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique UUID identifier for the document",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original name of the file uploaded by the user", max_length=255
                    ),
                ),
                (
                    "stored_filename",
                    models.CharField(
                        help_text="Sanitized unique filename on storage server",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(help_text="Stored file path", upload_to="documents/%Y/%m/%d/"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Document"),
                            ("docx", "Word Document"),
                            ("txt", "Plain Text"),
                        ],
                        db_index=True,
                        help_text="Document format type (pdf, docx, txt)",
                        max_length=10,
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "mime_type",
                    models.CharField(help_text="Validated MIME type of the file", max_length=100),
                ),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of file content for integrity and duplicate tracking",
                        max_length=64,
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True, help_text="Normalized text extracted from document", null=True
                    ),
                ),
                (
                    "llm_response",
                    models.JSONField(
                        blank=True,
                        help_text="Structured JSON result generated by LLM analysis",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current processing lifecycle status",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Detailed error message if processing failed",
                        null=True,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Celery background task ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of background processing retry attempts"
                    ),
                ),
                (
                    "processing_started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when text extraction/LLM processing started",
                        null=True,
                    ),
                ),
                (
                    "processing_completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when processing completed (success or fail)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when document upload record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when document record was last updated"
                    ),
                ),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="doc_status_created_idx"),
                    models.Index(fields=["file_type", "created_at"], name="doc_type_created_idx"),
                    models.Index(fields=["content_hash"], name="doc_content_hash_idx"),
                ],
            },
        ),
    ]
