import uuid
from typing import Any

from django.db import models
from django.utils.translation import gettext_lazy as _


class DocumentStatus(models.TextChoices):
    PENDING = "PENDING", _("Pending")
    PROCESSING = "PROCESSING", _("Processing")
    COMPLETED = "COMPLETED", _("Completed")
    FAILED = "FAILED", _("Failed")


class FileType(models.TextChoices):
    PDF = "pdf", _("PDF Document")
    DOCX = "docx", _("Word Document")
    TXT = "txt", _("Plain Text")


class Document(models.Model):
    objects = models.Manager()

    id: Any = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text=_("Unique UUID identifier for the document"),
    )
    original_filename: Any = models.CharField(
        max_length=255,
        help_text=_("Original name of the file uploaded by the user"),
    )
    stored_filename: Any = models.CharField(
        max_length=255,
        unique=True,
        help_text=_("Sanitized unique filename on storage server"),
    )
    file: Any = models.FileField(
        upload_to="documents/%Y/%m/%d/",
        help_text=_("Stored file path"),
    )
    file_type: Any = models.CharField(
        max_length=10,
        choices=FileType.choices,
        db_index=True,
        help_text=_("Document format type (pdf, docx, txt)"),
    )
    file_size: Any = models.BigIntegerField(
        help_text=_("File size in bytes"),
    )
    mime_type: Any = models.CharField(
        max_length=100,
        help_text=_("Validated MIME type of the file"),
    )
    content_hash: Any = models.CharField(
        max_length=64,
        db_index=True,
        help_text=_("SHA-256 hash of file content for integrity and duplicate tracking"),
    )
    extracted_text: Any = models.TextField(
        null=True,
        blank=True,
        help_text=_("Normalized text extracted from document"),
    )
    llm_response: Any = models.JSONField(
        null=True,
        blank=True,
        help_text=_("Structured JSON result generated by LLM analysis"),
    )
    status: Any = models.CharField(
        max_length=20,
        choices=DocumentStatus.choices,
        default=DocumentStatus.PENDING,
        db_index=True,
        help_text=_("Current processing lifecycle status"),
    )
    error_message: Any = models.TextField(
        null=True,
        blank=True,
        help_text=_("Detailed error message if processing failed"),
    )
    task_id: Any = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        db_index=True,
        help_text=_("Celery background task ID"),
    )
    retry_count: Any = models.PositiveIntegerField(
        default=0,
        help_text=_("Number of background processing retry attempts"),
    )
    processing_started_at: Any = models.DateTimeField(
        null=True,
        blank=True,
        help_text=_("Timestamp when text extraction/LLM processing started"),
    )
    processing_completed_at: Any = models.DateTimeField(
        null=True,
        blank=True,
        help_text=_("Timestamp when processing completed (success or fail)"),
    )
    created_at: Any = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text=_("Timestamp when document upload record was created"),
    )
    updated_at: Any = models.DateTimeField(
        auto_now=True,
        help_text=_("Timestamp when document record was last updated"),
    )

    class Meta:
        db_table = "documents"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["status", "created_at"], name="doc_status_created_idx"),
            models.Index(fields=["file_type", "created_at"], name="doc_type_created_idx"),
            models.Index(fields=["content_hash"], name="doc_content_hash_idx"),
        ]

    def __str__(self):
        return f"Document({self.id}, {self.original_filename}, status={self.status})"
